#!/usr/bin/env python3


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    N = int(input())
    C = list(input())
    Rc = len(list(filter(lambda x:x=="R",C)))
    Wc = len(C) - Rc
    c = 0
    for i in range(Rc):
        if C[i] == "W":
            c+=1
    # print(Rc)
    # print(Wc)
    print(c)
    pass

if __name__ == '__main__':
    main()
