#!/usr/bin/env python3
import sys


def solve(K: str):
    T=[]
    for i in range(int(K)):
        T.append('ACL')
    T = "".join(T)
    return print(T)


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = next(tokens)  # type: str
    solve(K)

if __name__ == '__main__':
    main()